name: Pull Request Builder

on:
  pull_request:

env:
  GRADLE_USER_HOME: .gradle

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source-code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Synchronise cache 1/2
        uses: actions/cache@v1
        with:
          path: .gradle/wrapper
          key: gradle-cache-wrapper-${{ hashFiles('core/build.gradle') }}

      - name: Synchronise cache 2/2
      - uses: actions/cache@v1
        with:
          path: .gradle/caches
          key: gradle-cache-caches-${{ hashFiles('core/build.gradle') }}

      - name: Build
        run: ./gradlew --no-daemon build

      - name: Upload Static Analysis for core
        uses: actions/upload-artifact@v1.0.0
        if: success() || failure()
        with:
          name: static-analysis-core
          path: core/build/reports

      - name: Upload Static Analysis for dmoe
        uses: actions/upload-artifact@v1.0.0
        if: success() || failure()
        with:
          name: static-analysis-mobile
          path: demo/build/reports

      - name: Upload Unit Tests for core
        uses: actions/upload-artifact@v1.0.0
        if: success() || failure()
        with:
          name: unit-tests-mobile
          path: core/build/test-results

      - name: Upload Unit Tests for demo
        uses: actions/upload-artifact@v1.0.0
        if: success() || failure()
        with:
          name: unit-tests-mobile
          path: demo/build/test-results
