name: Snapshot Builder

on:
  push:
    branches:
      - develop

env:
  GRADLE_USER_HOME: .gradle

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source-code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Synchronise cache 1/2
        uses: actions/cache@v1
        with:
          path: .gradle/wrapper
          key: gradle-cache-wrapper-${{ hashFiles('**/build.gradle') }}

      - name: Synchronise cache 2/2
        uses: actions/cache@v1
        with:
          path: .gradle/caches
          key: gradle-cache-caches-${{ hashFiles('**/build.gradle') }}

      - name: Build
        run: ./gradlew --no-daemon build

      - name: Upload snapshot
        run: ./gradlew bintrayUpload -PdryRun=false -PbintraySnapshot=true -PbintrayOrg=${{ secrets.BINTRAY_ORG }} -PbintrayRepo=${{ secrets.BINTRAY_REPO_SNAPSHOT }} -PbintrayUser=${{ secrets.BINTRAY_USER }} -PbintrayKey=${{ secrets.BINTRAY_KEY_SNAPSHOT }}

      - name: Notify slack if success
        if: success()
        uses: novoda/github-slack-action@master
        with:
          color: good
          text: New No-Player <https://bintray.com/novoda-oss/snapshots/no-player|snapshot> available
          webhook: ${{ secrets.SLACK_NOS }}

      - name: Notify slack if failure
        if: failure()
        uses: novoda/github-slack-action@master
        with:
          color: danger
          text: No-Player snapshot build failed
          webhook: ${{ secrets.SLACK_NOS }}
